description: |
  Download COVID-19 data in HK from the Internet.
executors:
  default:
    description: |
      Basic Docker image
    docker:
    - image: cimg/base:2020.01
jobs:
  all:
    description: |
      Checkout Git Repo.
    executor: default
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "ac:89:99:c4:d9:0e:90:66:0c:f1:5c:57:2e:46:4f:0e"
    - run:
        command: |
          pwd
          ls -lah
          git status
          git config user.email "hkkenneth@gmail.com"
          git config user.name "CircleCI Job"
          git checkout master
          date=$(date '+%Y-%m-%d')
          mkdir $date
          cd $date
          curl -O https://www.chp.gov.hk/files/pdf/local_situation_covid19_en.pdf
          git add local_situation_covid19_en.pdf
          curl -O https://www.chp.gov.hk/files/pdf/local_situation_covid19_tc.pdf
          git add local_situation_covid19_tc.pdf
          curl -O https://www.chp.gov.hk/files/pdf/building_list_eng.pdf
          git add building_list_eng.pdf
          curl -O https://www.chp.gov.hk/files/pdf/building_list_chi.pdf
          git add building_list_chi.pdf
          git commit --allow-empty -am "Automatic commit from CircleCI [skip ci]"
          git push origin master
        name: Git Checkout Curl Commit Push
  download:
    description: |
      Download COVID-19 data in HK from the Internet.
    executor: default
    steps:
    - run:
        command: curl -O https://www.chp.gov.hk/files/pdf/local_situation_covid19_en.pdf
        name: download-local-situation-en-pdf
    - run:
        command: curl -O https://www.chp.gov.hk/files/pdf/local_situation_covid19_tc.pdf
        name: download-local-situation-tc-pdf
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - all
  nightly:
    triggers:
      - schedule:
          cron: "*/5 * * * *"
          filters:
            branches:
              only:
                - circleci-project-setup
    jobs:
      - all
